=== edemiaochu/szewtwin-core/core/backend/src/assets/Settings/Schemas/Base.Schema.json
{
  "$comment": "This schema describes the meta-structure of an szewTwin Settings Schema file. It is used to provide a guide for the schema files themselves.",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "required": [
    "schemaPrefix",
    "description"
  ],
  "schemaPrefix": "szewtwin/core/base",
  "description": "meta-schema for all szewTwin settings schemas",
  "properties": {
    "settingDefs": {
      "type": "object",
      "description": "A group of setting definitions."
    },
    "typeDefs": {
      "type": "object",
      "description": "A group of type definitions that can be extended in setting definitions."
    },
    "schemaPrefix": {
      "type": "string",
      "description": "The unique prefix of the schema."
    },
    "description": {
      "type": "string",
      "description": "A description of the schema."
    },
    "order": {
      "type": "integer",
      "description": "An integer value used to sort the schema in a user interface list of multiple schemas, where schemas of lower order are sorted before those with higher order."
    }
  }
}

=== edemiaochu/szewtwin-core/core/backend/src/assets/Settings/Schemas/Workspace.Schema.json
{
  "$schema": "./Base.Schema.json",
  "description": "settings for workspaces",
  "schemaPrefix": "szewtwin/core/workspace",
  "settingDefs": {
    "settingsWorkspaces": {
      "description": "An array of resourceName, WorkspaceDb properties, each of which holds a Settings.Dictionary. Each entry also holds the settings priority for loading the dictionary.",
      "type": "array",
      "items": {
        "type": "object",
        "extends": "szewtwin/core/workspace/workspaceDb",
        "properties": {
          "resourceName": {
            "type": "string",
            "description": "the name of the string resource holding the settings dictionary in this WorkspaceDb",
            "default": "settingsDictionary"
          },
          "priority": {
            "type": "number",
            "description": "the SettingsPriority for the settingsDictionary",
            "default": 500
          }
        }
      }
    }
  },
  "typeDefs": {
    "workspaceDb": {
      "type": "object",
      "description": "WorkspaceDb properties",
      "required": [
        "containerId",
        "baseUri"
      ],
      "properties": {
        "dbName": {
          "type": "string",
          "description": "the name of the database within its cloud container. If not present, defaults to 'workspace-db'."
        },
        "baseUri": {
          "type": "string",
          "description": "the baseUri for the container, without trailing slash (e.g., https://containers.szewtwinjs.org)"
        },
        "containerId": {
          "type": "string",
          "description": "the containerId of this cloud container. Usually a Guid"
        },
        "storageType": {
          "type": "string",
          "description": "one of: 'azure', 'aws', 'google'",
          "default": "azure"
        },
        "description": {
          "type": "string",
          "description": "information about what is in this workspace"
        },
        "loadingHelp": {
          "type": "string",
          "description": "in case there is a problem loading this workspace, show this message"
        },
        "isPublic": {
          "type": "boolean",
          "description": "whether the cloud container is public (doesn't require authentication)",
          "default": false
        },
        "version": {
          "type": "string",
          "description": "the (semver) range of acceptable versions",
          "default": "^1"
        },
        "includePrerelease": {
          "type": "boolean",
          "description": "include prerelease in acceptable versions"
        },
        "prefetch": {
          "type": "boolean",
          "description": "if true, pre-fetch all of the data from the cloud in the background"
        },
        "syncOnConnect": {
          "type": "boolean",
          "description": "if false, do not attempt to synchronize with cloud when workspace is loaded",
          "hidden": true
        }
      }
    },
    "workspaceDbList": {
      "type": "array",
      "combineArray": true,
      "items": {
        "type": "object",
        "extends": "szewtwin/core/workspace/workspaceDb"
      }
    }
  }
}

=== edemiaochu/szewtwin-core/core/backend/src/test/assets/TestSettings.schema.json
{
  "$schema": "../../assets/Settings/Base.Schema.json",
  "description": "the settings for test application 1",
  "schemaPrefix": "testApp",
  "settingDefs": {
    "list/multiSelectModifier": {
      "type": "string",
      "enum": [
        "ctrlCmd",
        "alt"
      ],
      "enumDescriptions": [
        "ctrl key.",
        "alt key."
      ],
      "default": "ctrlCmd",
      "description": "multiSelectModifier"
    },
    "categories": {
      "type": "array",
      "description": "possible categories",
      "items": {
        "type": "string",
        "description": "category names"
      }
    },
    "list/openMode": {
      "type": "string",
      "enum": [
        "singleClick",
        "doubleClick"
      ],
      "default": "singleClick",
      "description": "openModeModifier"
    },
    "list/horizontalScrolling": {
      "type": "boolean",
      "default": false,
      "description": "horizontalScrolling setting"
    },
    "tree/indent": {
      "type": "number",
      "default": 8,
      "minimum": 0,
      "maximum": 40,
      "description": "tree indent setting"
    },
    "tree/blah": {
      "type": "boolean",
      "default": true,
      "description": "the setting for blah"
    },
    "fontList": {
      "type": "array",
      "description": "array of fonts to load",
      "items": {
        "type": "object",
        "extends": "testApp/font"
      }
    }
  },
  "typeDefs": {
    "font": {
      "type": "object",
      "description": "a single font",
      "required": [
        "workspace",
        "fontName"
      ],
      "properties": {
        "workspace": {
          "type": "object",
          "extends": "szewtwin/core/workspace/workspaceDb",
          "description": "workspaceDb for font",
          "required": [
            "workspaceLimit"
          ],
          "properties": {
            "workspaceLimit": {
              "type": "integer"
            }
          }
        },
        "fontName": {
          "type": "string",
          "description": "name of font within resource container"
        },
        "fontType": {
          "type": "string",
          "description": "the type of the font"
        }
      }
    }
  }
}
